<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BaseDataSeeder extends Seeder
{
    public function run(): void
    {
        // Inserir dados de produtos_base conforme base_script.sql
        DB::table('produtos_base')->insert([
            ['prod_cod' => ' PRD001', 'prod_nome' => '   Teclado  Mecânico   RGB  ', 'prod_cat' => 'PERIFERICOS', 'prod_subcat' => 'TECLADOS', 'prod_desc' => 'Teclado com iluminação RGB e switches azuis', 'prod_fab' => 'HyperTech', 'prod_mod' => 'HT-KEY-RGB', 'prod_cor' => 'Preto', 'prod_peso' => '1,2kg ', 'prod_larg' => '45 cm', 'prod_alt' => '5 CM ', 'prod_prof' => '15cm ', 'prod_und' => 'UN ', 'prod_atv' => true, 'prod_dt_cad' => '2025/10/10'],
            ['prod_cod' => 'prd002 ', 'prod_nome' => ' Mouse óptico  sem fio', 'prod_cat' => 'Periféricos ', 'prod_subcat' => 'Mouses', 'prod_desc' => 'Mouse com conexão wireless 2.4GHz', 'prod_fab' => 'TechPro', 'prod_mod' => 'TP-MOUSE-X', 'prod_cor' => ' Preto ', 'prod_peso' => ' 95g ', 'prod_larg' => '6cm', 'prod_alt' => '3 CM', 'prod_prof' => '10cm', 'prod_und' => ' un', 'prod_atv' => true, 'prod_dt_cad' => '10-10-2025'],
            ['prod_cod' => 'PRD003', 'prod_nome' => 'Monitor 24" Full HD', 'prod_cat' => 'MONITORES', 'prod_subcat' => 'LCD', 'prod_desc' => 'Monitor 1080p HDMI e VGA', 'prod_fab' => 'ViewBest', 'prod_mod' => 'VB-24HD', 'prod_cor' => 'Preto', 'prod_peso' => '3.5 KG', 'prod_larg' => '53,2cm ', 'prod_alt' => '32cm ', 'prod_prof' => ' 12 cm ', 'prod_und' => 'un', 'prod_atv' => true, 'prod_dt_cad' => '2025-10-12'],
            ['prod_cod' => 'PRD004', 'prod_nome' => 'Cadeira gamer Reclinável ', 'prod_cat' => 'Móveis ', 'prod_subcat' => 'Cadeiras', 'prod_desc' => 'Cadeira ergonômica com apoio de braço', 'prod_fab' => 'ComfortSeat', 'prod_mod' => 'CS-GAMER-R', 'prod_cor' => 'Vermelha', 'prod_peso' => ' 16,3 kg', 'prod_larg' => '70 CM ', 'prod_alt' => ' 120 cm', 'prod_prof' => '60 CM', 'prod_und' => 'UN', 'prod_atv' => true, 'prod_dt_cad' => '15/10/2025'],
            ['prod_cod' => ' PRD005', 'prod_nome' => 'HEADSET gamer 7.1', 'prod_cat' => 'Periféricos', 'prod_subcat' => 'Headsets', 'prod_desc' => 'Headset com som surround 7.1 e microfone retrátil', 'prod_fab' => 'SoundMax', 'prod_mod' => 'SM-HS71', 'prod_cor' => ' Preto ', 'prod_peso' => ' 350G ', 'prod_larg' => '18cm', 'prod_alt' => '20 CM ', 'prod_prof' => '10 cm', 'prod_und' => 'UN', 'prod_atv' => false, 'prod_dt_cad' => '2025.10.09'],
            ['prod_cod' => 'PRD006', 'prod_nome' => 'SSD 1TB NVMe', 'prod_cat' => 'COMPONENTES', 'prod_subcat' => 'ARMAZENAMENTO', 'prod_desc' => 'SSD NVMe M.2 2280, leitura 3500MB/s', 'prod_fab' => 'DataFast', 'prod_mod' => 'DF-NV1TB', 'prod_cor' => 'Prata', 'prod_peso' => '8g', 'prod_larg' => '8cm', 'prod_alt' => '0,2cm', 'prod_prof' => '2,2cm', 'prod_und' => 'UN', 'prod_atv' => true, 'prod_dt_cad' => '2023-05-20'],
            ['prod_cod' => 'PRD007', 'prod_nome' => 'Placa de Vídeo RTX 4060', 'prod_cat' => 'COMPONENTES', 'prod_subcat' => 'GPUS', 'prod_desc' => '8GB GDDR6, 3072 cores CUDA', 'prod_fab' => 'GraphiCore', 'prod_mod' => 'GC-RTX4060', 'prod_cor' => 'Preto', 'prod_peso' => '1.2kg', 'prod_larg' => '24cm', 'prod_alt' => '11.5cm', 'prod_prof' => '4cm', 'prod_und' => 'UN', 'prod_atv' => true, 'prod_dt_cad' => '2024/01/15'],
            ['prod_cod' => 'PRD008', 'prod_nome' => 'Processador Core i7', 'prod_cat' => 'COMPONENTES', 'prod_subcat' => 'CPUS', 'prod_desc' => '12ª geração, 12 núcleos, 4.9GHz', 'prod_fab' => 'ChipTech', 'prod_mod' => 'CT-I712700', 'prod_cor' => 'Prata', 'prod_peso' => '50g', 'prod_larg' => '4.5cm', 'prod_alt' => '4.5cm', 'prod_prof' => '0.5cm', 'prod_und' => 'UN', 'prod_atv' => true, 'prod_dt_cad' => '2023.11.30'],
            ['prod_cod' => 'PRD009', 'prod_nome' => 'Memória RAM 16GB', 'prod_cat' => 'COMPONENTES', 'prod_subcat' => 'MEMORIAS', 'prod_desc' => 'DDR4 3200MHz, CL16', 'prod_fab' => 'MemSpeed', 'prod_mod' => 'MS-D416G', 'prod_cor' => 'Preta', 'prod_peso' => '40g', 'prod_larg' => '13.3cm', 'prod_alt' => '3cm', 'prod_prof' => '0.8cm', 'prod_und' => 'UN', 'prod_atv' => true, 'prod_dt_cad' => '2023/08/22'],
            ['prod_cod' => 'PRD010', 'prod_nome' => 'Fonte 750W 80 Plus', 'prod_cat' => 'COMPONENTES', 'prod_subcat' => 'FONTES', 'prod_desc' => 'Modular, certificação Gold', 'prod_fab' => 'PowerMax', 'prod_mod' => 'PM-750G', 'prod_cor' => 'Preta', 'prod_peso' => '2.1kg', 'prod_larg' => '16cm', 'prod_alt' => '15cm', 'prod_prof' => '8.6cm', 'prod_und' => 'UN', 'prod_atv' => true, 'prod_dt_cad' => '2024-02-10'],
            ['prod_cod' => 'PRD011', 'prod_nome' => 'Gabinete Gamer', 'prod_cat' => 'ACESSORIOS', 'prod_subcat' => 'GABINETES', 'prod_desc' => 'Mid Tower, com lateral em vidro', 'prod_fab' => 'CaseMaster', 'prod_mod' => 'CM-T500', 'prod_cor' => 'Branco', 'prod_peso' => '6.5kg', 'prod_larg' => '47cm', 'prod_alt' => '50cm', 'prod_prof' => '22cm', 'prod_und' => 'UN', 'prod_atv' => true, 'prod_dt_cad' => '2023.12.05'],
            ['prod_cod' => 'PRD012', 'prod_nome' => 'Water Cooler 240mm', 'prod_cat' => 'COMPONENTES', 'prod_subcat' => 'REFRIAMENTO', 'prod_desc' => 'Radiador duplo, RGB', 'prod_fab' => 'CoolFlow', 'prod_mod' => 'CF-W240', 'prod_cor' => 'Preto', 'prod_peso' => '1.1kg', 'prod_larg' => '27.5cm', 'prod_alt' => '12cm', 'prod_prof' => '5.2cm', 'prod_und' => 'UN', 'prod_atv' => false, 'prod_dt_cad' => '2024/03/18'],
        ]);

        // Inserir dados de precos_base conforme base_script.sql
        DB::table('precos_base')->insert([
            ['prc_cod_prod' => ' PRD001 ', 'prc_valor' => ' 499,90 ', 'prc_moeda' => 'brl', 'prc_desc' => '5%', 'prc_acres' => '0', 'prc_promo' => '474,90', 'prc_dt_ini_promo' => '2025/10/10', 'prc_dt_fim_promo' => '2025-10-20', 'prc_dt_atual' => '2025-10-15', 'prc_origem' => 'SISTEMA ERP', 'prc_tipo_cli' => 'VAREJO', 'prc_vend_resp' => 'Marcos Silva', 'prc_obs' => 'Produto em destaque', 'prc_status' => 'ativo'],
            ['prc_cod_prod' => 'prd002', 'prc_valor' => '120.50', 'prc_moeda' => 'BRL ', 'prc_desc' => ' 0', 'prc_acres' => '0', 'prc_promo' => '120.50', 'prc_dt_ini_promo' => '10-10-2025', 'prc_dt_fim_promo' => null, 'prc_dt_atual' => '2025-10-16', 'prc_origem' => 'MIGRACAO', 'prc_tipo_cli' => 'ATACADO', 'prc_vend_resp' => ' Julia S.', 'prc_obs' => null, 'prc_status' => 'ativo'],
            ['prc_cod_prod' => 'PRD003', 'prc_valor' => '1.099,00', 'prc_moeda' => 'brl ', 'prc_desc' => '10%', 'prc_acres' => null, 'prc_promo' => '989,10', 'prc_dt_ini_promo' => '2025.10.10', 'prc_dt_fim_promo' => '2025.10.25', 'prc_dt_atual' => '16/10/2025', 'prc_origem' => 'API INTERNA', 'prc_tipo_cli' => 'VAREJO', 'prc_vend_resp' => ' Carlos Souza ', 'prc_obs' => 'Desconto aplicado via API', 'prc_status' => 'ativo'],
            ['prc_cod_prod' => ' prd004', 'prc_valor' => ' 899.99', 'prc_moeda' => 'brl', 'prc_desc' => null, 'prc_acres' => '5%', 'prc_promo' => null, 'prc_dt_ini_promo' => '15/10/2025', 'prc_dt_fim_promo' => '30/10/2025', 'prc_dt_atual' => '2025/10/16', 'prc_origem' => 'ERP LEGADO', 'prc_tipo_cli' => 'VAREJO', 'prc_vend_resp' => 'Jéssica M.', 'prc_obs' => 'Campanha de Outubro', 'prc_status' => 'ativo'],
            ['prc_cod_prod' => 'PRD005 ', 'prc_valor' => 'sem preço', 'prc_moeda' => 'BRL', 'prc_desc' => null, 'prc_acres' => null, 'prc_promo' => null, 'prc_dt_ini_promo' => null, 'prc_dt_fim_promo' => null, 'prc_dt_atual' => '2025-10-10', 'prc_origem' => 'ERP LEGADO', 'prc_tipo_cli' => 'VAREJO', 'prc_vend_resp' => 'Pedro L.', 'prc_obs' => 'Sem preço cadastrado', 'prc_status' => 'inativo'],
            ['prc_cod_prod' => 'PRD006', 'prc_valor' => '389,90', 'prc_moeda' => 'BRL', 'prc_desc' => '15%', 'prc_acres' => '2%', 'prc_promo' => '331,42', 'prc_dt_ini_promo' => '2024.06.01', 'prc_dt_fim_promo' => '2024.06.30', 'prc_dt_atual' => '2024-05-28', 'prc_origem' => 'SISTEMA ERP', 'prc_tipo_cli' => 'VAREJO', 'prc_vend_resp' => 'Ana Costa', 'prc_obs' => 'Promoção semestral', 'prc_status' => 'ativo'],
            ['prc_cod_prod' => 'PRD007', 'prc_valor' => '2.899,00', 'prc_moeda' => 'brl', 'prc_desc' => '8%', 'prc_acres' => null, 'prc_promo' => '2.667,08', 'prc_dt_ini_promo' => '2024/04/15', 'prc_dt_fim_promo' => '2024/05/15', 'prc_dt_atual' => '2024-04-10', 'prc_origem' => 'API INTERNA', 'prc_tipo_cli' => 'ATACADO', 'prc_vend_resp' => 'Roberto Lima', 'prc_obs' => 'Desconto por volume', 'prc_status' => 'ativo'],
            ['prc_cod_prod' => 'PRD008', 'prc_valor' => '1.899,00', 'prc_moeda' => 'BRL', 'prc_desc' => '12%', 'prc_acres' => '3%', 'prc_promo' => '1.671,12', 'prc_dt_ini_promo' => '2024-03-01', 'prc_dt_fim_promo' => '2024-03-31', 'prc_dt_atual' => '2024.02.25', 'prc_origem' => 'ERP LEGADO', 'prc_tipo_cli' => 'VAREJO', 'prc_vend_resp' => 'Fernanda R.', 'prc_obs' => 'Liquidação estoque', 'prc_status' => 'ativo'],
            ['prc_cod_prod' => 'PRD009', 'prc_valor' => '299,90', 'prc_moeda' => 'brl', 'prc_desc' => '20%', 'prc_acres' => '0', 'prc_promo' => '239,92', 'prc_dt_ini_promo' => '2024.05.20', 'prc_dt_fim_promo' => '2024.06.20', 'prc_dt_atual' => '2024/05/15', 'prc_origem' => 'SISTEMA ERP', 'prc_tipo_cli' => 'ATACADO', 'prc_vend_resp' => 'Carlos Santos', 'prc_obs' => 'Queima de estoque', 'prc_status' => 'ativo'],
            ['prc_cod_prod' => 'PRD010', 'prc_valor' => '699,00', 'prc_moeda' => 'BRL', 'prc_desc' => '5%', 'prc_acres' => '1%', 'prc_promo' => '664,05', 'prc_dt_ini_promo' => '2024-04-01', 'prc_dt_fim_promo' => '2024-04-30', 'prc_dt_atual' => '2024-03-28', 'prc_origem' => 'API INTERNA', 'prc_tipo_cli' => 'VAREJO', 'prc_vend_resp' => 'Mariana O.', 'prc_obs' => 'Promoção relâmpago', 'prc_status' => 'ativo'],
            ['prc_cod_prod' => 'PRD011', 'prc_valor' => '450,00', 'prc_moeda' => 'brl', 'prc_desc' => '25%', 'prc_acres' => null, 'prc_promo' => '337,50', 'prc_dt_ini_promo' => '2024/06/10', 'prc_dt_fim_promo' => '2024/07/10', 'prc_dt_atual' => '2024.06.05', 'prc_origem' => 'ERP LEGADO', 'prc_tipo_cli' => 'VAREJO', 'prc_vend_resp' => 'Paulo H.', 'prc_obs' => 'Dia dos namorados', 'prc_status' => 'ativo'],
            ['prc_cod_prod' => 'PRD012', 'prc_valor' => '0', 'prc_moeda' => 'BRL', 'prc_desc' => null, 'prc_acres' => null, 'prc_promo' => null, 'prc_dt_ini_promo' => null, 'prc_dt_fim_promo' => null, 'prc_dt_atual' => '2024-03-20', 'prc_origem' => 'SISTEMA ERP', 'prc_tipo_cli' => 'VAREJO', 'prc_vend_resp' => 'Lucas T.', 'prc_obs' => 'Produto descontinuado', 'prc_status' => 'inativo'],
        ]);
    }
}
